### ISSUE TITLE
Make Jumbotron CTA dynamic

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/starterkit-mustache-bootstrap#5]
Need a dynamic CTA for jumbotron. It's optional.

Also add dynamic `{{url}}` to the link

**Comment by frostyweather** [comment]
Added `{{# cta }}` wrapper around the CTA button. Also added `{{ url }}` to make the link dynamic. Should I add separate url for cta link so it isn't set to the default?

**Comment by frostyweather** [comment]
This has been addressed. Close #5
