### ISSUE TITLE
Media Object Variants

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/starterkit-mustache-bootstrap#6]
- Add dynamic `{{ url }}`
- Working pattern will need to have dynamic `{{# mediaLeft }}` and  `{{# mediaRight }}`

**Comment by frostyweather** [comment]
Added the `{{# mediaLeft }}` and `{{# mediaRight }}` sections before and after the body respectively. I set mediaLeft to true and mediaRight to false in the JSON so only the left would show up. Also added the dynamic URL. Close #6.
